// <auto-generated />
using System;
using IT410Project.Lib.EfCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IT410Project.Lib.EfCore.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20260310165903_LongProject")]
    partial class LongProject
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("IT410Project.Lib.EfCore.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("DATETIME");

                    b.Property<bool>("IsRepeating")
                        .HasColumnType("BIT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("DATETIME");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("IT410Project.Lib.EfCore.Entities.Sleep", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("DATETIME");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quality")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RepeatDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("DATETIME");

                    b.HasKey("Id");

                    b.ToTable("Sleep");
                });

            modelBuilder.Entity("IT410Project.Models.LongProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalWorkHours")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("LongProjects");
                });

            modelBuilder.Entity("IT410Project.Models.LongProjectDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("LongProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LongProjectId");

                    b.ToTable("LongProjectDays");
                });

            modelBuilder.Entity("IT410Project.Models.LongProjectDay", b =>
                {
                    b.HasOne("IT410Project.Models.LongProject", "LongProject")
                        .WithMany("ProjectDays")
                        .HasForeignKey("LongProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LongProject");
                });

            modelBuilder.Entity("IT410Project.Models.LongProject", b =>
                {
                    b.Navigation("ProjectDays");
                });
#pragma warning restore 612, 618
        }
    }
}
